plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation "com.cobblemon:neoforge:${cobblemon_version}"

    runtimeOnly "thedarkcolour:kotlinforforge-neoforge:${kff_version}"

    compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}:api"
    runtimeOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}"

    implementation("io.wispforest:accessories-neoforge:${accessories_version}+${minecraft_version}")

    runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"
}

sourceSets.main.resources { srcDir 'src/generated/resources' }